blank_issues_enabled: false
contact_links:
  - name: Help & Support
    url: https://github.com/Thavarshan/cerberus/issues
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
